version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-code-editor-app
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
