version: '3.8'
services:
  frontend:
    container_name: react-code-editor-app
    volumes:
      - './:/app'
      - '/app/node_modules'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
